### ISSUE TITLE
Runtime errors on Python 3.7

### ISSUE THREAD

**Issue by duckontheweb** [cloudsen12/easystac#1]
Thanks for this library, it fills a really interesting niche!

It looks like support for Python 3.7 was removed in 86a5a244820285e1f06453abdc2df7bcdc32508e, but the library can still be installed on that version of Python, leading to the following runtime error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-1-b49ba6bc5e87>](https://localhost:8080/#) in <module>()
      1 import leafmap
----> 2 import easystac as es
      3 from datetime import datetime

3 frames
[/usr/local/lib/python3.7/dist-packages/stackstac/rio_reader.py](https://localhost:8080/#) in <module>()
      5 import threading
      6 import weakref
----> 7 from typing import TYPE_CHECKING, Optional, Protocol, Tuple, Type, Union
      8 
      9 import numpy as np

ImportError: cannot import name 'Protocol' from 'typing' (/usr/lib/python3.7/typing.py)
```

If Python 3.7 is truly not supported, then it would probably be worth restricting the version of Python that this can be installed on in `setup.py` using [`python_requires`](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html?highlight=python_requires#python-requirement). However, if the Python 3.7 compatibility issues are not too difficult to resolve it might be worth supporting that issue. I came across this when trying to use `easystac` in a Google Colab notebook, which runs 3.7, so it supporting 3.7 would make it easier to use in that environment.

I'm happy to put in a PR for either approach if you let me know which direction you would like to go.

**Comment by duckontheweb** [comment]
Ah, my mistake. It looks like the ImportError is coming from `stackstac` and not `easystac`. I can raise an issue there instead.

**Comment by davemlz** [comment]
Ohhhh. Thanks for noticing it! I totally forgot to pin the Python version for that!
